steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --no-cache
      - -t
      - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - -f
      - Dockerfile

  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - --platform=managed
      - --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - --update-env-vars=COMMIT_SHA=$COMMIT_SHA
      - --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - --region=$_DEPLOY_REGION
      - --quiet

images:
  - $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE

substitutions:
  _AR_HOSTNAME: asia-northeast3-docker.pkg.dev
  _AR_PROJECT_ID: economic-freedum
  _AR_REPOSITORY: cloud-run-source-deploy
  _DEPLOY_REGION: asia-northeast3
  _SERVICE_NAME: economic-agent
  _TRIGGER_ID: 07bffe95-dc27-4128-bc60-a30e69c4b7ee
