module.exports = {
  // 가격 관찰 목록과 분리된 즉시 공시 알림 목록. 꼭 필요한 종목만 명시한다.
  // 보유 종목은 포트폴리오에서 자동으로 포함된다.
  criticalAlerts: [],
  preopen: [
    { symbol: '^KS11', name: 'KOSPI' },
    { symbol: '^KQ11', name: 'KOSDAQ' },
    { symbol: 'KRW=X', name: 'USD/KRW' },
    { symbol: '005930.KS', name: '삼성전자' },
    { symbol: '000660.KS', name: 'SK하이닉스' },
  ],
  usopen: [
    { symbol: 'SPY', name: 'S&P 500 ETF' },
    { symbol: 'QQQ', name: 'Nasdaq 100 ETF' },
    { symbol: 'SOXX', name: 'Semiconductor ETF' },
    { symbol: 'NVDA', name: 'NVIDIA' },
    { symbol: 'AMD', name: 'AMD' },
    { symbol: 'MU', name: 'Micron Technology' },
    { symbol: 'TSM', name: 'TSMC ADR' },
    { symbol: 'GOOGL', name: 'Alphabet A' },
    { symbol: 'AAPL', name: 'Apple' },
    { symbol: 'MSFT', name: 'Microsoft' },
    { symbol: 'TSLA', name: 'Tesla' },
  ],
  close: [
    { symbol: '^KS11', name: 'KOSPI' },
    { symbol: '^KQ11', name: 'KOSDAQ' },
    { symbol: 'KRW=X', name: 'USD/KRW' },
    { symbol: '005930.KS', name: '삼성전자' },
    { symbol: '000660.KS', name: 'SK하이닉스' },
  ],
  domesticMomentum: [
    { symbol: '005930.KS', name: '삼성전자' },
    { symbol: '000660.KS', name: 'SK하이닉스' },
    { symbol: '005380.KS', name: '현대차' },
    { symbol: '000270.KS', name: '기아' },
    { symbol: '012450.KS', name: '한화에어로스페이스' },
    { symbol: '267250.KS', name: 'HD현대' },
    { symbol: '329180.KS', name: 'HD현대중공업' },
    { symbol: '055550.KS', name: '신한지주' },
  ],
  globalMomentum: [
    { symbol: 'MU', name: 'Micron Technology' },
    { symbol: 'GOOGL', name: 'Alphabet A' },
    { symbol: 'NVDA', name: 'NVIDIA' },
    { symbol: 'AMD', name: 'AMD' },
    { symbol: 'TSM', name: 'TSMC ADR' },
    { symbol: 'AVGO', name: 'Broadcom' },
  ],
  global: [
    { symbol: 'SPY', name: 'S&P 500 ETF' },
    { symbol: 'QQQ', name: 'Nasdaq 100 ETF' },
    { symbol: 'SOXX', name: 'Semiconductor ETF' },
    { symbol: 'MU', name: 'Micron Technology' },
    { symbol: 'NVDA', name: 'NVIDIA' },
    { symbol: 'AMD', name: 'AMD' },
    { symbol: 'TSM', name: 'TSMC ADR' },
    { symbol: 'CL=F', name: 'WTI Oil' },
    { symbol: 'HG=F', name: 'Copper' },
    { symbol: 'GC=F', name: 'Gold' },
    { symbol: '^VIX', name: 'VIX' },
    { symbol: 'DX-Y.NYB', name: 'Dollar Index' },
    { symbol: 'KRW=X', name: 'USD/KRW' },
  ],
};
