module.exports = {
  BATCH_SIZE: 20,
  MIN_SCORE: 4,
  URGENT_SCORE: 5,
  MAX_URGENT_ALERTS_PER_RUN: Number(process.env.MAX_URGENT_ALERTS_PER_RUN || 1),
  MAX_URGENT_ALERTS_PER_DAY: Number(process.env.MAX_URGENT_ALERTS_PER_DAY || 2),
  URGENT_EVENT_DEDUP_HOURS: Number(process.env.URGENT_EVENT_DEDUP_HOURS || 24),
  MAX_SEEN: 15000,
  RSS_TIMEOUT_MS: 10000,
  TIMEZONE: 'Asia/Seoul',
};
