module.exports = {
  BATCH_SIZE: 20,
  MIN_SCORE: 4,
  URGENT_SCORE: 5,
  MAX_URGENT_ALERTS_PER_RUN: Number(process.env.MAX_URGENT_ALERTS_PER_RUN || 3),
  MAX_SEEN: 15000,
  RSS_TIMEOUT_MS: 10000,
  TELEGRAM_DELAY_MS: 1000,
  TIMEZONE: 'Asia/Seoul',
};
